//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kutuphaneEntities3 : DbContext
    {
        public kutuphaneEntities3()
            : base("name=kutuphaneEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_tbl> admin_tbl { get; set; }
        public virtual DbSet<emanet_tbl> emanet_tbl { get; set; }
        public virtual DbSet<kitap_tbl> kitap_tbl { get; set; }
        public virtual DbSet<okur_tbl> okur_tbl { get; set; }
    }
}
