//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emanet_tbl
    {
        public int id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string isbnno { get; set; }
        public string kitapad { get; set; }
        public string yazar { get; set; }
        public string tarih { get; set; }
        public string tc { get; set; }
        public string durum { get; set; }
    }
}
